import React, { useState } from 'react';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Mail, Send, X } from 'lucide-react';
import { supabase } from '@/integrations/supabase/client';
import { useToast } from '@/hooks/use-toast';

interface Message {
  id: string;
  type: 'user' | 'ai';
  content: string;
  timestamp: Date;
}

interface EmailChatHistoryModalProps {
  isOpen: boolean;
  onClose: () => void;
  messages: Message[];
  coachName: string;
}

const EmailChatHistoryModal: React.FC<EmailChatHistoryModalProps> = ({
  isOpen,
  onClose,
  messages,
  coachName
}) => {
  const [email, setEmail] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const { toast } = useToast();

  const formatChatHistory = () => {
    const timestamp = new Date().toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    });

    let formattedChat = `📋 REENTRY NAVIGATOR - CHAT HISTORY\n`;
    formattedChat += `Coach: ${coachName}\n`;
    formattedChat += `Session Date: ${timestamp}\n`;
    formattedChat += `${'='.repeat(50)}\n\n`;

    messages.forEach((message, index) => {
      const sender = message.type === 'ai' ? `🤖 ${coachName}` : '👤 You';
      const messageTime = message.timestamp.toLocaleTimeString('en-US', {
        hour: '2-digit',
        minute: '2-digit'
      });
      
      formattedChat += `[${messageTime}] ${sender}:\n`;
      // Clean up message content for email
      const cleanContent = message.content
        .replace(/<strong[^>]*>(.*?)<\/strong>/g, '**$1**')
        .replace(/<em[^>]*>(.*?)<\/em>/g, '*$1*')
        .replace(/<br\s*\/?>/g, '\n')
        .replace(/&nbsp;/g, ' ')
        .trim();
      
      formattedChat += `${cleanContent}\n\n`;
    });

    formattedChat += `${'='.repeat(50)}\n`;
    formattedChat += `📱 EMERGENCY CONTACTS:\n`;
    formattedChat += `• Emergency: 911\n`;
    formattedChat += `• Crisis Support: 988\n`;
    formattedChat += `• Local Resources: 211\n\n`;
    formattedChat += `This chat history was generated by the Reentry Navigator AI system.\n`;
    formattedChat += `For additional support, visit your community learning platform.\n`;
    formattedChat += `For comprehensive resource navigation, call 2-1-1.\n`;

    return formattedChat;
  };

  const handleSendEmail = async () => {
    if (!email.trim()) {
      toast({
        title: "Email Required",
        description: "Please enter your email address.",
        variant: "destructive"
      });
      return;
    }

    // Basic email validation
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (!emailRegex.test(email)) {
      toast({
        title: "Invalid Email",
        description: "Please enter a valid email address.",
        variant: "destructive"
      });
      return;
    }

    setIsLoading(true);

    try {
      const chatHistory = formatChatHistory();
      
      const { error } = await supabase.functions.invoke('send-contact-email', {
        body: {
          name: 'Chat History Request',
          email: email,
          subject: `Your Chat History with ${coachName}`,
          message: chatHistory,
          isAutoResponse: true
        }
      });

      if (error) {
        throw error;
      }

      toast({
        title: "Email Sent Successfully!",
        description: "Your chat history has been sent to your email address."
      });

      setEmail('');
      onClose();
    } catch (error) {
      console.error('Error sending chat history email:', error);
      toast({
        title: "Email Failed",
        description: "Unable to send your chat history. Please try again or save the conversation manually.",
        variant: "destructive"
      });
    } finally {
      setIsLoading(false);
    }
  };

  if (!isOpen) return null;

  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent className="max-w-md">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Mail className="h-5 w-5 text-primary" />
            Email Chat History
          </DialogTitle>
        </DialogHeader>

        <div className="space-y-4">
          <div className="text-sm text-muted-foreground">
            Get a copy of your conversation with {coachName} sent to your email. 
            This includes all messages, resources, and guidance shared during this session.
          </div>

          <div className="space-y-2">
            <Label htmlFor="email">Your Email Address</Label>
            <Input
              id="email"
              type="email"
              placeholder="your.email@example.com"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              disabled={isLoading}
            />
          </div>

          <div className="bg-muted/50 border rounded-lg p-3">
            <h4 className="font-medium text-sm mb-2">What will be included:</h4>
            <ul className="text-xs text-muted-foreground space-y-1">
              <li>• Complete conversation transcript</li>
              <li>• Resource recommendations and links</li>
              <li>• Date and time stamps</li>
              <li>• Coach information and specialties</li>
            </ul>
          </div>

          <div className="text-xs text-muted-foreground">
            <strong>Privacy Note:</strong> Your email will only be used to send this chat history. 
            We respect your privacy and will not store or share your email address.
          </div>

          <div className="flex gap-2 pt-2">
            <Button
              variant="outline"
              className="flex-1"
              onClick={onClose}
              disabled={isLoading}
            >
              <X className="h-4 w-4 mr-1" />
              Cancel
            </Button>
            <Button
              className="flex-1"
              onClick={handleSendEmail}
              disabled={isLoading || !email.trim()}
            >
              <Send className="h-4 w-4 mr-1" />
              {isLoading ? 'Sending...' : 'Send Email'}
            </Button>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
};

export default EmailChatHistoryModal;