-- Insert Ohio resources into the resources table with proper UUID generation
INSERT INTO public.resources (
  name,
  organization,
  phone,
  website,
  address,
  city,
  county,
  type,
  verified,
  justice_friendly,
  rating,
  description,
  state_code,
  created_at,
  updated_at
) VALUES
  (
    'Columbus Night Shelter',
    'Columbus Community Shelter Network',
    '+16145551212',
    'https://example.org/columbus-shelter',
    '123 Safe St, Columbus, OH',
    'Columbus',
    'Franklin',
    'Housing',
    'partner',
    true,
    4.6,
    'Emergency beds and case management. Call before 6pm for availability.',
    'OH',
    now(),
    now()
  ),
  (
    'Cuyahoga Legal Aid Hotline',
    'Legal Aid Society of Cleveland',
    '+12165550123',
    'https://example.org/cle-legal-aid',
    null,
    'Cleveland',
    'Cuyahoga',
    'Legal',
    'partner',
    true,
    4.8,
    'Free legal advice and intake for civil issues including housing and benefits.',
    'OH',
    now() - interval '1 day',
    now() - interval '1 day'
  ),
  (
    'Second Chance Employers Network',
    'Ohio Workforce Alliance',
    null,
    'https://example.org/second-chance-employers',
    null,
    'Statewide',
    'Franklin',
    'Employment',
    'community',
    true,
    4.2,
    'Directory of employers open to justice-impacted applicants across Ohio.',
    'OH',
    now() - interval '2 days',
    now() - interval '2 days'
  ),
  (
    'Cincinnati Transitional Housing',
    'Queen City Reentry',
    '+15135551234',
    null,
    null,
    'Cincinnati',
    'Hamilton',
    'Housing',
    'community',
    true,
    4.1,
    'Short-term transitional units with onsite support services.',
    'OH',
    now() - interval '5 days',
    now() - interval '5 days'
  ),
  (
    'Mindfulness & Wellness Tools',
    'Forward Focus Elevation',
    null,
    'https://forwardfocuselevation.org',
    null,
    'Statewide',
    'Franklin',
    'Health',
    'partner',
    true,
    4.7,
    'Free tools for emotional resilience and stress reduction.',
    'OH',
    now() - interval '1 day',
    now() - interval '1 day'
  ),
  (
    'Financial Literacy & Credit Education',
    'Forward Focus Elevation',
    null,
    'https://forwardfocuselevation.org',
    null,
    'Statewide',
    'Franklin',
    'Financial',
    'partner',
    true,
    4.9,
    'Free ebook and classes to build financial stability.',
    'OH',
    now() - interval '3 days',
    now() - interval '3 days'
  ),
  (
    'GED Fast Track',
    'Ohio Adult Education',
    null,
    'https://example.org/ged-ohio',
    null,
    'Dayton',
    'Montgomery',
    'Education',
    'community',
    true,
    4.0,
    'Preparation courses and free testing vouchers for eligible learners.',
    'OH',
    now() - interval '10 days',
    now() - interval '10 days'
  ),
  (
    'Mobile Food Pantry Schedule',
    'Toledo Food Bank',
    null,
    'https://example.org/toledo-food',
    null,
    'Toledo',
    'Lucas',
    'Family',
    'community',
    true,
    4.5,
    'Weekly mobile pantry with fresh produce and staples.',
    'OH',
    now() - interval '4 days',
    now() - interval '4 days'
  ),
  (
    'Behavioral Health Crisis Line',
    'Ohio Mental Health Services',
    '+18002738255',
    'https://example.org/ohio-crisis',
    null,
    'Statewide',
    'Franklin',
    'Health',
    'partner',
    true,
    4.3,
    '24/7 crisis counseling and referral to local services.',
    'OH',
    now(),
    now()
  ),
  (
    'Apprenticeship Finder',
    'Ohio Trades Coalition',
    null,
    'https://example.org/apprenticeships-oh',
    null,
    'Columbus',
    'Franklin',
    'Employment',
    'community',
    true,
    4.1,
    'Entry-level apprenticeships in skilled trades with paid training.',
    'OH',
    now() - interval '7 days',
    now() - interval '7 days'
  );